### ISSUE TITLE
Broken in Node v8.3.0

### ISSUE THREAD

**Issue by gwin003** [isaacs/node-graceful-fs#116]
I understand that this package only supports up through v7, but are there are plans to fix this issue for Node v8?

`Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:40:20
    at Object.<anonymous> (C:\Dev\OlympusCore\trunk\DMSVehicle\DMSVehicle\DMSVehicle.Client\node_modules\graceful-fs\fs.js:11:1)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)`

**Comment by ferm10n** [comment]
Works fine in node v8.7.0 on Windows 7!

**Comment by jstephens7** [comment]
We've run into a similar problem with an outdated version of localizr, which used this npm:

Error: Cannot find module 'internal/errors' 
at Function.Module._resolveFilename (module.js:527:15) 
at Function.Module._load (module.js:476:23) 
at Module.require (module.js:568:17) 
at require (internal/module.js:11:18) 
at evalmachine.<anonymous>:36:16 
at Object.<anonymous> (/var/www/node_modules/localizr/node_modules/graceful-fs/fs.js:11:1) 
at Module._compile (module.js:624:30) 
at Object.Module._extensions..js (module.js:635:10) 
at Module.load (module.js:545:32) 
at tryModuleLoad (module.js:508:12) 
at Function.Module._load (module.js:500:3) 
at Module.require (module.js:568:17) 
at require (internal/module.js:11:18) 
at Object.<anonymous> (/var/www/node_modules/localizr/node_modules/graceful-fs/graceful-fs.js:3:27) 
at Module._compile (module.js:624:30) 
at Object.Module._extensions..js (module.js:635:10) 
at Module.load (module.js:545:32) 
at tryModuleLoad (module.js:508:12) 
at Function.Module._load (module.js:500:3) 
at Module.require (module.js:568:17) 
at require (internal/module.js:11:18) 
at Object.<anonymous> (/var/www/node_modules/localizr/index.js:18:10)
